namespace VoidFlow
{
    // The item lists as they were when saves still stored items by their place in the list
    // (up to October 2026): old saves are read back through these, by name
    public static class LegacySkinNames
    {
        public static readonly string[] Gloves =
        {
            "Gloves",
            "Gloves | Nebula",
            "Gloves | Sunset Fade",
            "Gloves | Candy Swirl",
            "Gloves | Amber Stripe",
            "Gloves | Red Web",
            "Gloves | Emerald Nebula",
            "Gloves | Carbon",
            "Gloves | Gunmetal",
            "Gloves | Diamond Plate",
            "Gloves | Saddle",
            "Gloves | Tidewater Onyx",
            "Gloves | Black Marble",
            "Gloves | 24K Gold",
            "Gloves | Chrome",
            "Gloves | Holographic",
            "Gloves | Molten",
            "Gloves | Toxic",
            "Gloves | Sapphire",
            "Gloves | Ruby",
            "Gloves | Amethyst",
            "Gloves | Obsidian",
            "Gloves | Confetti",
            "Inferno Gauntlet",
            "Frost Talons",
            "Void Runes",
            "Dragonscale",
            "Plasma Knuckles",
            "Bonehand",
            "Crystal Gauntlet",
            "Seraph Wraps",
            "Storm Gauntlet",
            "Reaper Wraps"
        };
        public static readonly string[] Knives =
        {
            "Talon Knife",
            "Talon Knife | Nebula",
            "Talon Knife | Amber Stripe",
            "Talon Knife | Red Web",
            "Butterfly | Sunset Fade",
            "Butterfly | Candy Swirl",
            "Butterfly | Emerald Nebula",
            "Hollow Moon",
            "Tidebreaker",
            "Colossus",
            "Soul Reaper",
            "Frost Reaper",
            "Nova Saber",
            "Crimson Saber",
            "Shardfang",
            "Serpent Fang",
            "Dragon Claw",
            "Doom Axe",
            "Storm Sai",
            "Starlance",
            "Wraith Kris",
            "Inferno Reaper",
            "Void Saber",
            "Solar Saber",
            "Emerald Shard",
            "Talon Knife | Tidewater Onyx",
            "Talon Knife | Carbon",
            "Butterfly | Black Marble",
            "Butterfly | Smoke Onyx",
            "Talon Knife | Pearl Onyx",
            "Talon Knife | Desert Onyx",
            "Butterfly | Caramel Swirl",
            "Talon Knife | Glacier Onyx",
            "Butterfly | Amber Onyx",
            "Talon Knife | Crimson Onyx",
            "Butterfly | Crimson Onyx",
            "Butterfly | Storm Onyx",
            "Talon Knife | Violet Onyx",
            "Butterfly | Violet Onyx",
            "Butterfly | Obsidian",
            "Talon Knife | Confetti",
            "Butterfly | Magma Vein",
            "Talon Knife | Magma Vein",
            "Talon Knife | Molten",
            "Butterfly | Molten",
            "Butterfly | Lava Flow",
            "Talon Knife | Lava Flow",
            "Talon Knife | Plasma",
            "Butterfly | Plasma",
            "Butterfly | Toxic",
            "Talon Knife | Toxic",
            "Talon Knife | Void Flare",
            "Butterfly | Void Flare",
            "Butterfly | Frostbite",
            "Talon Knife | Frostbite",
            "Talon Knife | Shattered Ice",
            "Butterfly | Shattered Ice",
            "Butterfly | Sapphire",
            "Talon Knife | Sapphire",
            "Talon Knife | Amethyst",
            "Butterfly | Amethyst",
            "Butterfly | Ruby",
            "Talon Knife | Ruby",
            "Talon Knife | Chrome",
            "Butterfly | Chrome",
            "Butterfly | 24K Gold",
            "Talon Knife | 24K Gold",
            "Talon Knife | Copper",
            "Butterfly | Antique Gold",
            "Talon Knife | Holographic",
            "Butterfly | Holographic",
            "Talon Knife | Tempered",
            "Butterfly Knife",
            "M9 Bayonet",
            "Skeleton Knife",
            "Kukri Knife",
            "Kukri Knife | Sunset Fade",
            "Kukri Knife | Red Web",
            "Kukri Knife | Nebula",
            "Kukri Knife | Emerald Nebula",
            "Kukri Knife | Carbon",
            "M9 Bayonet | Sunset Fade",
            "M9 Bayonet | Nebula",
            "M9 Bayonet | Sapphire",
            "M9 Bayonet | Ruby",
            "M9 Bayonet | Red Web",
            "M9 Bayonet | Amber Stripe",
            "Skeleton Knife | Sunset Fade",
            "Skeleton Knife | Red Web",
            "Skeleton Knife | Nebula",
            "Skeleton Knife | Emerald Nebula",
            "Skeleton Knife | Black Marble",
            "Skeleton Knife | 24K Gold",
            "Abyss Talon",
            "Inferno Butterfly",
            "Frost Bayonet",
            "Phantom Skeleton",
            "Bloodmoon Kukri"
        };
        public static readonly string[] Snipers =
        {
            "Longreach",
            "Longreach | Nebula",
            "Longreach | Amber Stripe",
            "Longreach | Candy Swirl",
            "Longreach | Red Web",
            "Spectrum",
            "Crescent",
            "Leviathan",
            "Hellfire",
            "Stormcaller",
            "Clockwork",
            "Nebula Core",
            "Viper",
            "Grim Harvest",
            "Event Horizon",
            "Glitch",
            "Prism",
            "Deathwhisper",
            "Plasma Lance",
            "Seraph",
            "Longreach | Tidewater Onyx",
            "Longreach | Carbon",
            "Longreach | Diamond Plate",
            "Longreach | Grey Marble",
            "Longreach | White Marble",
            "Longreach | Gunmetal",
            "Longreach | Saddle",
            "Longreach | Desert Onyx",
            "Longreach | Caramel Swirl",
            "Longreach | Glacier Onyx",
            "Longreach | Amber Onyx",
            "Longreach | Crimson Onyx",
            "Longreach | Storm Onyx",
            "Longreach | Violet Onyx",
            "Longreach | Obsidian",
            "Longreach | Confetti",
            "Longreach | Magma Vein",
            "Longreach | Molten",
            "Longreach | Lava Flow",
            "Longreach | Plasma",
            "Longreach | Toxic",
            "Longreach | Void Flare",
            "Longreach | Frostbite",
            "Longreach | Shattered Ice",
            "Longreach | Sapphire",
            "Longreach | Amethyst",
            "Longreach | Ruby",
            "Longreach | Chrome",
            "Longreach | 24K Gold",
            "Longreach | Copper",
            "Longreach | Antique Gold",
            "Longreach | Holographic"
        };
        public static string[] Of(ItemSlot slot) => slot switch { ItemSlot.Primary => Snipers, ItemSlot.Hands => Gloves, _ => Knives };
    }
}
